src/app.py
from flask import Flask, render_template
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.jinja2')


from src.models.wishes.views import wish_blueprint
from src.models.users.views import user_blueprint
app.register_blueprint(wish_blueprint, url_prefix="/wishes")
app.register_blueprint(user_blueprint, url_prefix="/users")

src/models/users/views.py
from flask import Blueprint, request, session, url_for, redirect, render_template

from src.models.users.user import User
import src.models.users.errors as UserErrors
# import src.models.users.decorators as user_decorators
# from src.models.wishes import wish

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_wishes"))
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/login.jinja2')  # Send the user an error if their login was invalid


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        wish = request.form['wish']
        wish_keyword = request.form['wish_keyword']

        try:
            if User.register_user(email, password, wish, wish_keyword):
                session['email'] = email
                return redirect(url_for("wishes.index"))
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/register.jinja2')  # Send the user an error if their login was invalid


@user_blueprint.route('/wishes')
def user_wishes():
    user = User.find_by_email(session['email'])
    wishes = user.get_wishes(session['email'])
    return render_template('wishes/wish_page.jinja2', user=user, wishes=wishes)

# @user_blueprint.route('/alerts')
# @user_decorators.requires_login
# def user_alerts():
#     user = User.find_by_email(session['email'])
#     alerts = user.get_alerts()
#     return render_template('users/alerts.jinja2', alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


# @user_blueprint.route('/check_alerts/<string:user_id>')
# def check_user_alerts(user_id):
#     pass

src/models/wishes/views.py
from flask import Blueprint, render_template, request, url_for, redirect
from src.models.wishes.wish import Wish


wish_blueprint = Blueprint('wishes', __name__)


@wish_blueprint.route('/')
def index():
    wishes = Wish.all()
    return render_template('wishes/wish_index.jinja2', wishes=wishes)


@wish_blueprint.route('/wish')
def wish_page(wish_id):
    return render_template('wishes/wish_page.jinja2', wish=Wish.get_by_id(wish_id))


@wish_blueprint.route('/new', methods=['GET', 'POST'])
def new_wish():

    if request.method == 'POST':
        print('testing')

        # keyword = request.form['keyword']
        # description = request.form['description']

        wish = Wish(wish, wish_keyword)
        wish.save_to_mongo()

        return redirect(url_for('.index'))

    # return "You are adding a new wish"
    return render_template('wishes/new_wish.jinja2')

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wish For A World</title>

    {% include 'html_dependencies.jinja2' %}

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/" title="Home">W4AW</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('wishes.index') }}">Board of Wishes</a></li>
            </ul>
            {% if session['email'] %}
            <ul class="navbar navbar-nav navbar-right">
                <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
            </ul>
            {% else %}
            <ul class="navbar navbar-nav navbar-right">
                <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-register"></span> Sign up</a></li>
                <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
             </ul>
            {% endif %}
        </div>

    </div>
</nav>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}

<h1>THIS IS THE HOME PAGE!</h1>


{% endblock %}

src/templates/html_dependencies.jinja2
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Log in</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form-size">
       <form action="{{ url_for('users.register_user') }}" method="post">
           <div class="form-group">
               <label for="email">Email address</label>
               <input type="email" class="form-control" id="email" name="email" placeholder="Email">
           </div>
           <div class="form-group">
               <label for="password">Password</label>
               <input type="password" class="form-control" id="password" name="password" placeholder="Password">
           </div>
           <div class="form-group">
               <label for="wish">Complete the sentence: I wish for a world...</label>
               <input type="text" class="form-control" id="wish" name="wish" placeholder="Your Wish For A Better World">
           </div>
           <div class="form-group">
               <label for="wish_keyword">Choose a keyword for your wish</label>
               <input type="text" class="form-control" id="wish_keyword" name="wish_keyword" placeholder="Only one word, your wish's keyword">
           </div>
           <button type="submit" class="btn btn-default">Sign up</button>
       </form>
    </div>
{% endblock %}

src/templates/wishes/new_wish.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Add A New Wish</h1>
    </div>
    <div class="form">
        <form method="post">
            <div class="form-group">
                <label for="wish_keyword">Wish Keyword</label>
                <input type="text" class="form-control" id="wish_keyword" name="wish_keyword" placeholder="wish_Keyword">
            </div>

            <div class="form-group">
                <label for="description">Wish Description</label>
                <input type="text" class="form-control" id="description" name="description" placeholder="your description here"
                       aria-describedby="descriptionBlock">
                <span id="descriptionBlock" class="help-block">Your wish will be added to our Database</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/wishes/wish_index.jinja2
{% extends "base.jinja2" %}
{% block content %}

<div class="page-header">
    <h1>A Board of Wishes</h1>
</div>
<div class="list-group">
    {% for wish in wishes %}
        <a href="{{ url_for('wishes.wish_page', wish_id=wish._id) }}" class="list-group-item">
            <h4 class="list-group-item-title">{{ wish.wish }}</h4>
            <h5 class="list-group-item-title" style="text-transform:uppercase;">{{ wish.wish_keyword }}</h5>
            <p class="list-group-item-text">{{ wish.user_email }}</p>

        </a>
    {% endfor %}
</div>
    <a class="btn btn-success" href="{{ url_for('wishes.new_wish') }}">
        <span class="glyphicon glyphicon-plus"></span>Add A Wish
    </a>
{% endblock %}

src/templates/wishes/wish_page.jinja2
{% extends "base.jinja2" %}
{% block content %}

<div>User Email</div>

{{ user.email }}

<div class="page-header">
        <h1>I wish for a world...</h1>
    </div>
    <div class="list-group">
        {% for wish in wishes %}
            <h4 class="list-group-item-heading">
                <span class="glyphicon glyphicon-remove-circle"></span>
                {{ wish.wish }}
            </h4>
        {% endfor %}
    </div>
{% endblock %}